Test class implementation.
cesar-school/eta-unit-testing-project-2019.2-Recife pull request #12
Opened 2020-08-17 21:32 UTC by Widancassio

Entrega projeto testes unitários ETA - 2019.2.

2020-09-22 21:14 UTC, miltonmc requested changes
Para recuperar a nota você precisa trabalhar nos comentários que deixei nesse PR. Nessa etapa, A nota limite será 7.

Estou recebendo as mudanças até o dia 4 de outubro.

Qualquer duvida pode perguntar no PR que eu repondo aqui mesmo.

2020-09-22 21:14 UTC, miltonmc commented on src/main/java/school/cesar/eta/unit/PersonMock.java
> +	public void addToFamily(Person person) {
O método não deveria ter sido reescrever. Com isso, se o método original for acidentalmente alterado os teste que utilizam esse método continuarão passando.

2020-09-22 21:14 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +		personMock.addToFamily(personMock);
Como o método `Person.addToFamily()` foi sobrescrito em `PersonMock`, esse teste está testando o `PersonMock.addToFamily()`

2020-09-22 21:14 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +		personMock.addToFamily(personFamily);
Como o método `Person.addToFamily()` foi sobrescrito em `PersonMock`, esse teste está testando o `PersonMock.addToFamily()`

2020-09-22 21:14 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +		person.setBirthday(LocalDate.of(2020, differentMonth, differentDay));
Se esse teste for executado no dia 31/12/2021, o que aconteceria com esse teste? `DateTimeException `

https://docs.oracle.com/javase/8/docs/api/java/time/LocalDate.html#of-int-int-int-

2020-09-22 21:14 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +		person.setBirthday(LocalDate.of(2020, differentMonth, sameDay));
Se esse teste for executado no dia 31/12/2021, o que aconteceria com esse teste? `DateTimeException `

https://docs.oracle.com/javase/8/docs/api/java/time/LocalDate.html#of-int-int-int-

2020-09-22 21:14 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +		person.setBirthday(LocalDate.of(2020, sameMonth, differentDay));
Se esse teste for executado no dia 31/12/2021, o que aconteceria com esse teste? `DateTimeException `

https://docs.oracle.com/javase/8/docs/api/java/time/LocalDate.html#of-int-int-int-

2020-09-22 21:14 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +		Assertions.assertTrue(person.isBirthdayToday());
A data retornada pelo `LocalDate.now()` é calculado no momento em que o método é chamado, então por frações de segundo o dia calculado pode ser diferente do calculado pela chamada do `getNow()` o que pode provocar intermitências no resultado do teste.

Evite basear seus testes em variáveis do sistema!

2020-09-22 21:14 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +		person.addToFamily(personRelative);
Esta chamada acopla o sucesso do teste a correta implementação `addToFamily()`. Testes unitários devem isolar o cenário que está sendo testado.

2020-09-30 22:16 UTC, Widancassio commented
Seguem alterações no projeto final.

2020-10-19 22:07 UTC, miltonmc requested changes

2020-10-19 22:07 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +		personMock.addToFamily(personMock);
Adicionando uma instancia de `Person`  a própria `family` você não consegue garantir que o código foi testado corretamente, pois é possível que ele tenha sido inserido no caso anterior.

2020-10-20 19:18 UTC, Widancassio commented
Correção final

2020-10-27 06:13 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +		person.addToFamily(personRelative);
@Widancassio  esse comentário ainda não foi resolvido

2020-10-27 12:28 UTC, Widancassio commented
Nova correção

2020-10-29 16:14 UTC, miltonmc approved these changes
Aprovado!

2020-10-29 16:40 UTC, miltonmc commented
A nota foi  atualizadas no sistema!

Qualquer duvida estou a disposição. 😄

2020-10-29 16:40 UTC, closed without merging