Projeto Final - Ewertton Souza
cesar-school/eta-unit-testing-project-2019.2-Recife pull request #14
Opened 2020-08-18 01:04 UTC by eossTS

Criação dos testes do projeto final
Ewertton Oliveira Silva de Souza

2020-09-22 21:15 UTC, miltonmc requested changes
Para recuperar a nota você precisa trabalhar nos comentários que deixei nesse PR. Nessa etapa, A nota limite será 7.

Estou recebendo as mudanças até o dia 4 de outubro.

Qualquer duvida pode perguntar no PR que eu repondo aqui mesmo.

2020-09-22 21:15 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +        Assertions.assertFalse(person.isBirthdayToday());
Como o método `getNow()` está chamando `LocalDate.now()`, teste falhará se for executado no dia 23/05.

2020-09-22 21:15 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +        Assertions.assertFalse(person.isBirthdayToday());;
Como o método `getNow()` está chamando `LocalDate.now()`, teste falhará se for executado no dia 23/08.

2020-09-22 21:15 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +        Assertions.assertTrue(person.isBirthdayToday());;
A data retornada pelo `LocalDate.now()` é calculado no momento em que o método é chamado, então por frações de segundo o dia calculado pode ser diferente do calculado pela chamada do `getNow()` o que pode provocar intermitências no resultado do teste.

Evite basear seus testes em variáveis do sistema!

2020-09-22 21:15 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +       person.addToFamily(newMember);
Esta chamada acopla o sucesso do teste a correta implementação `addToFamily()`. Testes unitários devem isolar o cenário que está sendo testado.

2020-09-22 21:15 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +                Assertions.assertTrue(newMember.isFamily(newMember));
Testes unitários devem isolar o cenário que está sendo testado, sendo assim não deveria contar com a correta implementação do método `isFamily()`.

2020-10-02 22:11 UTC, eossTS commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +        Assertions.assertFalse(person.isBirthdayToday());
Alterações realizadas

2020-10-02 22:12 UTC, eossTS commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +        Assertions.assertTrue(person.isBirthdayToday());;
Alterações realizadas

2020-10-02 22:12 UTC, eossTS commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +       person.addToFamily(newMember);
Alterações realizadas

2020-10-02 22:12 UTC, eossTS commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +                Assertions.assertTrue(newMember.isFamily(newMember));
Alterações realizadas

2020-10-02 22:12 UTC, eossTS commented
Alterações realizadas

2020-10-19 22:32 UTC, miltonmc requested changes
Ainda faltam algumas alterações a serem feitas

2020-10-19 22:32 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +        Assertions.assertFalse(person.isBirthdayToday());
É preciso controlar o retorno do método `getNow()`, um das possibilidades é com uso de um stub. Enquanto isso não ocorre o resultado do teste será intermitente, variando com o dia em que é executado.

O mesmo ocorrerá com os próximos 2 testes.

2020-10-23 00:43 UTC, eossTS commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +        Assertions.assertFalse(person.isBirthdayToday());
Ajustes realizados

2020-10-27 06:15 UTC, miltonmc approved these changes
Aprovado!

2020-10-29 16:41 UTC, miltonmc commented
A nota foi  atualizadas no sistema!

Qualquer duvida estou a disposição. 😄

2020-10-29 16:41 UTC, closed without merging