[Commit Projeto] projeto finalizado
cesar-school/eta-unit-testing-project-2019.2-Recife pull request #19
Opened 2020-08-26 00:39 UTC by edimailzaProjects

Pull Request do projeto.

2020-09-22 04:52 UTC, miltonmc commented on eta-unit-testing-project-2019.2-Recife-main/src/main/java/school/cesar/eta/unit/PersonService.java
> +package school.cesar.eta.unit;
A classe PersonService faz parte do código de teste, por tanto deveria ser adicionado no diretório: `/src/test/java/`

2020-09-22 21:18 UTC, miltonmc requested changes
Para recuperar a nota você precisa trabalhar nos comentários que deixei nesse PR. Nessa etapa, A nota limite será 7.

Estou recebendo as mudanças até o dia 4 de outubro.

Qualquer duvida pode perguntar no PR que eu repondo aqui mesmo.

2020-09-22 21:18 UTC, miltonmc commented on eta-unit-testing-project-2019.2-Recife-main/src/main/java/school/cesar/eta/unit/PersonServiceInterface.java
> +package school.cesar.eta.unit;
A classe PersonServiceInterface faz parte do código de teste, por tanto deveria ser adicionado no diretório: `/src/test/java/`

2020-09-22 21:18 UTC, miltonmc commented on eta-unit-testing-project-2019.2-Recife-main/src/main/java/school/cesar/eta/unit/utils/FakePerson.java
> +package school.cesar.eta.unit.utils;
A classe FakePerson faz parte do código de teste, por tanto deveria ser adicionado no diretório: `/src/test/java/`

2020-09-22 21:18 UTC, miltonmc commented on eta-unit-testing-project-2019.2-Recife-main/src/test/java/school/cesar/eta/unit/PersonTest.java
> +package school.cesar.eta.unit;
A classe PersonTest faz parte do código de teste, por tanto deveria ter permanecido no diretório: `/src/test/java/`

2020-09-22 21:18 UTC, miltonmc commented on eta-unit-testing-project-2019.2-Recife-main/src/test/java/school/cesar/eta/unit/PersonTest.java
> +       boolean result = person.isBirthdayToday();
A data retornada pelo `LocalDate.now()` é calculado no momento em que o método é chamado, ~~então por frações de segundo o dia calculado pode ser diferente do calculado pela chamada do `getNow()`~~ o que pode provocar intermitências no resultado do teste.

Evite basear seus testes em variáveis do sistema!

2020-09-22 21:18 UTC, miltonmc commented on eta-unit-testing-project-2019.2-Recife-main/src/test/java/school/cesar/eta/unit/PersonTest.java
> +        fail();
Test não implementado

2020-09-22 21:18 UTC, miltonmc commented on eta-unit-testing-project-2019.2-Recife-main/src/test/java/school/cesar/eta/unit/PersonTest.java
> +    	person.setBirthday(LocalDate.of(year, month, (day -2)));
Se esse teste for executado no dia 01/01/2021, o que aconteceria com esse teste? `DateTimeException `

https://docs.oracle.com/javase/8/docs/api/java/time/LocalDate.html#of-int-int-int-

2020-09-22 21:18 UTC, miltonmc commented on eta-unit-testing-project-2019.2-Recife-main/src/test/java/school/cesar/eta/unit/PersonTest.java
> +        boolean result = person.isBirthdayToday();
A data retornada pelo `LocalDate.now()` é calculado no momento em que o método é chamado, então por frações de segundo o dia calculado pode ser diferente do calculado pela chamada do `getNow()` o que pode provocar intermitências no resultado do teste.

Evite basear seus testes em variáveis do sistema!

2020-09-22 21:18 UTC, miltonmc commented on eta-unit-testing-project-2019.2-Recife-main/src/test/java/school/cesar/eta/unit/PersonTest.java
> +        boolean result = person.isBirthdayToday();
A data retornada pelo `LocalDate.now()` é calculado no momento em que o método é chamado, então por frações de segundo o dia calculado pode ser diferente do calculado pela chamada do `getNow()` o que pode provocar intermitências no resultado do teste.

Evite basear seus testes em variáveis do sistema!

2020-09-22 21:18 UTC, miltonmc commented on eta-unit-testing-project-2019.2-Recife-main/src/test/java/school/cesar/eta/unit/PersonTest.java
> +    	service.addToFamily(person);
Esta chamada acopla o sucesso do teste a correta implementação do  método `addToFamily()`. Testes unitários devem isolar o cenário que está sendo testado.

2020-09-22 21:18 UTC, miltonmc commented on eta-unit-testing-project-2019.2-Recife-main/src/test/java/school/cesar/eta/unit/PersonTest.java
> +    	Assertions.assertTrue(person.isFamily(person));
Nesse caso o que está sendo testado é o stub criado mais a cima e não o código que deve ir para produção.

2020-09-22 21:18 UTC, miltonmc commented on eta-unit-testing-project-2019.2-Recife-main/src/test/java/school/cesar/eta/unit/PersonTest.java
> +       Assertions.assertFalse(person.isFamily(person));
Nesse caso o que está sendo testado é o stub criado mais a cima e não o código que deve ir para produção.

2020-09-22 21:18 UTC, miltonmc commented on eta-unit-testing-project-2019.2-Recife-main/src/test/java/school/cesar/eta/unit/PersonTest.java
> +        boolean result = relativePerson.isFamily(person);
Nesse caso o que está sendo testado é o método `isFamily()` que sobrescreveu o método original FakePerson e não o código que deve ir para produção.

2020-09-30 01:58 UTC, edimailzaProjects commented on eta-unit-testing-project-2019.2-Recife-main/src/test/java/school/cesar/eta/unit/PersonTest.java
> +       boolean result = person.isBirthdayToday();
Professor, neste caso específico, eu passei a data no passado para que ele sempre retorne falso independentemente do que o .now() trouxer. Eu gostaria se saber como executar este teste sem fazer o uso de  LocalDate, mas não vejo outra forma de fazer sem sobrecarga do método isBirthdayToday(), Ainda pensei no seguinte:
Person person = new Person() {
           @Override
           public boolean isBirthdayToday() {
               return false;
           }
       };
       
       boolean result = person.isBirthdayToday();
       Assertions.assertFalse(result);

Mas ele pede dia e mês diferente. Como eu não me recordo de ter visto na aula como tratar casos de métodos que utilizam variáveis do sistema, eu realmente não tenho ideia de como proceder neste caso. Você pode me ajudar?

2020-09-30 02:27 UTC, miltonmc commented on eta-unit-testing-project-2019.2-Recife-main/src/test/java/school/cesar/eta/unit/PersonTest.java
> +       boolean result = person.isBirthdayToday();
Olá me desculpe pelo comentário acima, ele foi impreciso!

O que ocorre com esse teste é que se ele for executado no dia 01/01 a chamada do `person.isBirthdayToday()` retornará `true`, o que fará o teste falhar.

Agora imagine que esse teste faz parte de uma suite de testes que é executada com frequência (algumas vezes por dia). Nesse cenário a equipe que trabalha no software, um dia por ano, não conseguirá gerar um build do projeto pq esse teste estaria falhando. A próxima falha aconteceria no 01/01/2021, depois novamente no 01/01/2022 e assim sucessivamente.

Para que isso não ocorra é preciso isolar a variável de ambiente, que é á data do sistema. O meio mais simples de fazer isso é por meio de um stub do método `getNow()` na classe `Person` que você está instanciando no `@BeforeEach`.

2020-09-30 13:18 UTC, edimailzaProjects commented on eta-unit-testing-project-2019.2-Recife-main/src/test/java/school/cesar/eta/unit/PersonTest.java
> +       boolean result = person.isBirthdayToday();
Acho que entendi sua ideia, só gostaria de confirmar se a implementei corretamente:

na classe PersonService, eu sobrescrevi o método getNow() e forcei o retorno :

@Override
    public LocalDate getNow()
    {  
        return LocalDate.parse("2020-01-01");
    }

Aí, lá na classe de teste eu usei:

@Test
    public void isBirthdayToday_differentMonthAndDay_false() {     
        PersonService service = new PersonService();
        person.setBirthday(service.getNow());
        boolean result = person.isBirthdayToday();
        Assertions.assertFalse(result);
       
    }

2020-09-30 19:15 UTC, edimailzaProjects commented on eta-unit-testing-project-2019.2-Recife-main/src/main/java/school/cesar/eta/unit/PersonServiceInterface.java
> +package school.cesar.eta.unit;
Professor, subi aqui minhas modificações, mas foi sem querer. Ainda me falta ajustar umas classes. Esta submissão ainda não é a versão final.

2020-09-30 19:35 UTC, miltonmc requested changes

2020-09-30 19:35 UTC, miltonmc commented on eta-unit-testing-project-2019.2-Recife-main/src/test/java/PersonTest.java
> +        PersonService service = new PersonService();
O código o código desse linha estava correto, não é preciso de nenhuma alteração!

Utilizando uma data fixa para que não houvesse nenhum tipo de variação nos dados a serem testados.

2020-09-30 19:35 UTC, miltonmc commented on eta-unit-testing-project-2019.2-Recife-main/src/test/java/PersonTest.java
> +        boolean result = person.isBirthdayToday();
o problema está aqui, quando o método `isBirthdayToday()` é chamado ele executará `LocalDate.now()` que pega a data, uma variável do sistema.

Crie um stub para o método `getNow()`, lá no `@BeforeEach`, que é onde `person` é instanciado.

2020-09-30 19:35 UTC, miltonmc commented on eta-unit-testing-project-2019.2-Recife-main/src/test/java/PersonTest.java
> +                return LocalDate.of(year, month, diferentDay-5);
Além de deixar o entendimento do teste difícil, o cálculo `diferentDay-5` pode resultar em valores que variam de -4 até 0, quando o dia é igual ou inferior a 5, o que resulta em `DateTimeException`.

https://docs.oracle.com/javase/8/docs/api/java/time/LocalDate.html#of-int-int-int-

Por que não utilizar uma data fixa aqui?

2020-09-30 19:35 UTC, miltonmc commented on eta-unit-testing-project-2019.2-Recife-main/src/test/java/PersonTest.java
> +        person.getNow();
Essa chamada não tem nenhuma utilidade para o nosso caso de teste

2020-09-30 19:35 UTC, miltonmc commented on eta-unit-testing-project-2019.2-Recife-main/src/test/java/PersonServiceInterface.java
> +
essa interface não é util para nossos testes, logo pode se removida.

2020-09-30 20:52 UTC, edimailzaProjects commented
Acredito que agora finalizei.

2020-09-30 20:54 UTC, edimailzaProjects commented on eta-unit-testing-project-2019.2-Recife-main/src/test/java/PersonServiceInterface.java
> +
Eu a removi e realizei algumas modificações. Consegui utilizar o Mockito em um caso de teste também.

2020-09-30 21:35 UTC, edimailzaProjects commented
Professor, submeti a versão final, mas por alguma razão muito estranha, meu eclipse está apontando pra uma branche diferente da atual, como mostra a imagem abaixo:
![image](https://user-images.githubusercontent.com/56605831/94742091-82fd4900-034b-11eb-8c69-ef8c5e9f4a79.png)
Você pode me ajudar a trocar para a branche correta?
O código está na versão final:


import static org.mockito.Mockito.mock;

import java.time.LocalDate;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mockito;
import org.mockito.junit.jupiter.MockitoExtension;
import org.mockito.junit.jupiter.MockitoSettings;
import org.mockito.quality.Strictness;

import school.cesar.eta.unit.Person;

@ExtendWith(MockitoExtension.class)
@MockitoSettings(strictness = Strictness.LENIENT)
public class PersonTest
{

    private Person person;

    @InjectMocks
    Person somePerson;

    @BeforeEach
    public void setup()
    {
        person = new Person()
        {
            @Override
            public LocalDate getNow()
            {
                return LocalDate.of(2000, 02, 20);
            }
        };
    }

    @Test
    public void getName_firstNameJonLastNameSnow_jonSnow()
    {
        person.setName("Jhon");
        person.setLastName("Snow");
        Assertions.assertEquals("JhonSnow", person.getName());

    }

    @Test
    public void getName_firstNameJonNoLastName_jon()
    {
        person.setName("Jhon");
        Assertions.assertEquals("Jhon", person.getName());
    }

    @Test
    public void getName_noFirstNameLastNameSnow_snow()
    {
        person.setLastName("Snow");
        Assertions.assertEquals("Snow", person.getName());
    }

    @Test
    public void getName_noFirstNameNorLastName_throwsException()
    {
        person.setName(null);
        person.setLastName(null);

        Assertions.assertThrows(RuntimeException.class, () -> {
            person.getName();
        });
    }

    @Test
    public void isBirthdayToday_differentMonthAndDay_false()
    {
        person.setBirthday(LocalDate.of(2000, 01, 21));
        boolean result = person.isBirthdayToday();
        Assertions.assertFalse(result);

    }

    @Test
    public void isBirthdayToday_sameMonthDifferentDay_false()
    {
        person.setBirthday(LocalDate.of(2000, 02, 21));
        boolean result = person.isBirthdayToday();
        Assertions.assertFalse(result);
    }

    @Test
    public void isBirthdayToday_sameMonthAndDay_true()
    {
        person.setBirthday(LocalDate.of(2000, 02, 20));
        boolean result = person.isBirthdayToday();
        Assertions.assertTrue(result);
    }

    @Test
    public void addToFamily_somePerson_familyHasNewMember()
    {
        person.addToFamily(somePerson);
        Assertions.assertTrue(person.isFamily(somePerson));

    }

    @Test
    public void addToFamily_somePerson_personAddedAlsoHasItsFamilyUpdated()
    {

    }

    @Test
    public void isFamily_nonRelativePerson_false()
    {
        person = mock(FakePerson.class);
        Mockito.when(person.isFamily(person)).thenReturn(false);
    }

    @Test
    public void isFamily_relativePerson_true()
    {
        FakePerson relativePerson = new FakePerson();
        boolean result = relativePerson.isFamily(person);
        Assertions.assertTrue(result);
    }
}

2020-09-30 21:51 UTC, edimailzaProjects commented
Consegui!! subi na branche correta!! :)

2020-10-19 21:53 UTC, miltonmc approved these changes

2020-10-19 21:53 UTC, miltonmc commented
Aprovada!

2020-10-29 16:44 UTC, miltonmc commented
A nota foi  atualizadas no sistema!

Qualquer duvida estou a disposição. 😄

2020-10-29 16:44 UTC, closed without merging