Projeto final Testes Unitário
cesar-school/eta-unit-testing-project-2019.2-Recife pull request #7
Opened 2020-08-15 21:54 UTC by DaniloLinhares

2020-09-22 21:08 UTC, miltonmc requested changes
Para recuperar a nota você precisa trabalhar nos comentários que deixei nesse PR. Nessa etapa, A nota limite será 7.

Estou recebendo as mudanças até o dia 4 de outubro.

Qualquer duvida pode perguntar no PR que eu repondo aqui mesmo.

2020-09-22 21:08 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +        Assertions.assertEquals("Jon",person.getFirstName());
O foco desse teste deveria ser o método `.getName()`, sendo assim esse `.assertEquals()` e o próximo, não são necessários. Ele pertenceria a outro caso de teste e  pode acabar falhando se `.getFirstName()` ou `.getLastName()` apresentar alguma falha em sua implementação.

2020-09-22 21:08 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +        Assertions.assertEquals("Snow",person.getLastName());
O foco desse teste deveria ser o método `.getName()`, sendo assim esse `.assertEquals()` não é necessários. Ele pertenceria a outro caso de teste e pode acabar falhando se `.getLastName()` apresentar alguma falha em sua implementação.

2020-09-22 21:08 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +        Assertions.assertEquals("Jon",person.getFirstName());
O foco desse teste deveria ser o método `.getName()`, sendo assim esse `.assertEquals()` não é necessários. Ele pertenceria a outro caso de teste e pode acabar falhando se `.getFirstName()` apresentar alguma falha em sua implementação.

2020-09-22 21:08 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +        Assertions.assertNotEquals(person.getBirthday().getMonth(),LocalDate.now().getMonth());
O foco desse teste deveria ser o método `.isBirthdayToday()`, sendo assim esse `.assertNotEquals()` e o próximo, não são necessários. Eles adicionam complexidade ao teste e na prática está testando funções do `LocalDate`.

2020-09-22 21:08 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +        Assertions.assertFalse(person.isBirthdayToday());
Essa verificação está dependendo da correta implantação do `getNow()`, logo o `isBirthdayToday()` não está sendo testado de forma unitária.

O teste falhará se executado no dia que não 02/09.

2020-09-22 21:08 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +        Assertions.assertEquals(person.getBirthday().getMonth(),LocalDate.now().getMonth());
O foco desse teste deveria ser o método `.isBirthdayToday()`, sendo assim esse `.assertEquals()` e o próximo `.assertNotEquals()`, não são necessários. Eles adicionam complexidade ao teste e na prática está testando funções do `LocalDate`.

2020-09-22 21:08 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +        Assertions.assertFalse(person.isBirthdayToday());
Essa verificação está dependendo da correta implantação do `getNow()`, logo o `isBirthdayToday()` não está sendo testado de forma unitária.

O teste falhará se executado no dia 02/08.

2020-09-22 21:08 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +        Assertions.assertTrue(personOne.isFamily(personTwo));
O senário a ser testado deveria ter sido se ao chamar o método `addToFamily()` o array `family` foi devidamente atualizado.

2020-09-22 21:08 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +        Assertions.assertTrue(personTwo.isFamily(personOne));
O senário a ser testado deveria ter sido se ao chamar o método `addToFamily()` o array `family` da pessoa passada como parâmetro foi devidamente atualizado.

2020-09-22 21:08 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +        person.addToFamily(personTwo);
Esta chamada acopla o sucesso do teste a correta implementação `addToFamily()`. Testes unitários devem isolar o cenário que está sendo testado.

2020-09-22 21:08 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +        Assertions.assertTrue(person.isBirthdayToday());
O teste falhará se executado em qualquer dia que não seja 14/08.

2020-09-29 15:40 UTC, DaniloLinhares commented
Boa tarde professor,
Resolvido os retornos solicitados.

2020-10-14 19:25 UTC, miltonmc approved these changes
Aprovado!

Deixei apenas uma observação.

2020-10-14 19:25 UTC, miltonmc commented on src/test/java/school/cesar/eta/unit/PersonTest.java
> +        LocalDate birthday = LocalDate.of(1988,7, 2);
O cenário testado foi `differentMonthSameDay`, o que está diferente do especificado no mome do teste `sameMonthDifferentDay`.

2020-10-29 16:40 UTC, miltonmc commented
A nota foi  atualizadas no sistema!

Qualquer duvida estou a disposição. 😄

2020-10-29 16:40 UTC, closed without merging